### ISSUE TITLE
relation extraction on Chinese ?

### ISSUE THREAD

**Issue by Jim0530** [plkmo/BERT-Relation-Extraction#15]
What is the purpose of adding config=>>>fine_tuning_task=semeval 
If I use it on Chinese what should I be aware of?
thanks

**Comment by plkmo** [comment]
the config --task allows for other tasks to be included in the future, such as fewrel.
For chinese, you would need chinese pre-trained BERT with appropriate tokenizers (such as jieba), You will also need entity recognizers for chinese which is not yet supported in spacy, in order to generated annotated data for pretraining/auto-inference, but otherwise the code would be largely unchanged.

**Comment by wangguanhua** [comment]
> What is the purpose of adding config=>>>fine_tuning_task=semeval
> If I use it on Chinese what should I be aware of?
> thanks



> What is the purpose of adding config=>>>fine_tuning_task=semeval
> If I use it on Chinese what should I be aware of?
> thanks

我觉得作者说的貌似不对，因为中文是按字切分的，所以不需要用jieba。我觉得我们应该需要更换预训练模型，然后把wordpiece换为中文的处理方式就好。
