### ISSUE TITLE
Fewrel task

### ISSUE THREAD

**Issue by arunzz** [plkmo/BERT-Relation-Extraction#5]
Hi 

How do I use this for few-shot classification task. Pls advise.

**Comment by plkmo** [comment]
For fewrel task, to infer an input, you have to take its output representation vector (from the trained EM-MTB model) and do a dot product comparison with the exemplar's representations. 
I will package that in a script that in due time, since right now I'm a little busy and don't yet have a satisfactory trained EM-MTB model, which takes a long time to optimize with current resources.

**Comment by vpvsankar** [comment]
Did you able to get satisfactory result for MTB model? Also can you provide codes for FewRel task

**Comment by plkmo** [comment]
fewrel 5 way 1 shot task added. MTB training requires more GPU than i can handle currently.
